<a href="https://colab.research.google.com/github/GAKUMAR3001/Advanced-AI---Data-Foundations/blob/main/Probability.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!wget https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/101/397/original/Sachin_ODI.csv

--2026-01-30 16:17:14--  https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/101/397/original/Sachin_ODI.csv
Resolving d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)... 3.169.201.14, 3.169.201.143, 3.169.201.165, ...
Connecting to d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)|3.169.201.14|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 26440 (26K) [text/plain]
Saving to: ‘Sachin_ODI.csv’

Sachin_ODI.csv      100%[===================>]  25.82K  --.-KB/s    in 0.002s

2026-01-30 16:17:14 (12.8 MB/s) - ‘Sachin_ODI.csv’ saved [26440/26440]

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

sachin_data  = pd.read_csv("Sachin_ODI.csv")

sachin_data .head()

,runs,NotOut,mins,bf,fours,sixes,sr,Inns,Opp,Ground,Date,Winner,Won,century
0,13,0,30,15,3,0,86.66,1,New Zealand,Napier,1995-02-16,New Zealand,False,False
1,37,0,75,51,3,1,72.54,2,South Africa,Hamilton,1995-02-18,South Africa,False,False
2,47,0,65,40,7,0,117.50,2,Australia,Dunedin,1995-02-22,India,True,False
3,48,0,37,30,9,1,160.00,2,Bangladesh,Sharjah,1995-04-05,India,True,False
4,4,0,13,9,1,0,44.44,2,Pakistan,Sharjah,1995-04-07,Pakistan,False,False

In [ ]:
sachin_data.shape

(360, 14)

In [ ]:
sachin_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   runs     360 non-null    int64
 1   NotOut   360 non-null    int64
 2   mins     360 non-null    object
 3   bf       360 non-null    int64
 4   fours    360 non-null    int64
 5   sixes    360 non-null    int64
 6   sr       360 non-null    float64
 7   Inns     360 non-null    int64
 8   Opp      360 non-null    object
 9   Ground   360 non-null    object
 10  Date     360 non-null    object
 11  Winner   360 non-null    object
 12  Won      360 non-null    bool
 13  century  360 non-null    bool
dtypes: bool(2), float64(1), int64(6), object(5)
memory usage: 34.6+ KB

In [ ]:
sample_space = sachin_data['runs'].unique()

In [ ]:
np.sort(sample_space)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  57,  60,  61,  62,  63,  64,  65,  67,  68,
        69,  70,  71,  72,  74,  77,  78,  79,  80,  81,  82,  83,  85,
        86,  87,  88,  89,  90,  91,  93,  94,  95,  96,  97,  98,  99,
       100, 101, 102, 104, 105, 110, 111, 112, 113, 114, 117, 118, 120,
       122, 123, 124, 127, 128, 134, 137, 138, 139, 140, 141, 143, 146,
       152, 163, 175, 186, 200])

In [ ]:
sachin_data['runs'].nunique()

122

In [ ]:
### Which ODI matches did Sachin Tendulkar score more than 50 runs in,
#and India won, and what were the details of those matches?

In [ ]:
event_A = sachin_data[sachin_data['runs'] >= 100]

In [ ]:
sachin_data[sachin_data['runs'] >= 100]

,runs,NotOut,mins,bf,fours,sixes,sr,Inns,Opp,Ground,Date,Winner,Won,century
5,112,1,137,107,15,1,104.67,2,Sri Lanka,Sharjah,1995-04-09,India,True,True
12,127,1,175,138,15,1,92.02,2,Kenya,Cuttack,1996-02-18,India,True,True
15,137,0,198,137,8,5,100.00,1,Sri Lanka,Delhi,1996-03-02,Sri Lanka,False,True
20,100,0,-,111,9,1,90.09,1,Pakistan,Singapore,1996-04-05,Pakistan,False,True
23,118,0,-,140,8,2,84.28,1,Pakistan,Sharjah,1996-04-15,India,True,True
27,110,0,-,138,5,1,79.71,1,Sri Lanka,Colombo (RPS),1996-08-28,Sri Lanka,False,True
41,114,0,157,126,14,0,90.47,1,South Africa,Mumbai,1996-12-14,India,True,True
47,104,0,121,97,8,1,107.21,2,Zimbabwe,Benoni,1997-02-09,India,True,True
55,117,0,188,137,13,2,85.40,2,New Zealand,Bengaluru,1997-05-14,India,True,True
85,100,0,132,89,5,7,112.35,2,Australia,Kanpur,1998-04-07,India,True,True
91,143,0,187,131,9,5,109.16,2,Australia,Sharjah,1998-04-22,Australia,False,True
92,134,0,195,131,12,3,102.29,2,Australia,Sharjah,1998-04-24,India,True,True
95,100,1,156,103,13,0,97.08,2,Kenya,Kolkata,1998-05-31,India,True,True
99,128,0,182,131,8,2,97.70,1,Sri Lanka,Colombo (RPS),1998-07-07,India,True,True
101,127,1,155,130,13,1,97.69,2,Zimbabwe,Bulawayo,1998-09-26,India,True,True
104,141,0,191,128,13,3,110.15,1,Australia,Dhaka,1998-10-28,India,True,True
107,118,1,173,112,14,2,105.35,2,Zimbabwe,Sharjah,1998-11-08,India,True,True
110,124,1,140,92,12,6,134.78,2,Zimbabwe,Sharjah,1998-11-13,India,True,True
116,140,1,114,101,16,3,138.61,1,Kenya,Bristol,1999-05-23,India,True,True
123,120,0,191,141,11,2,85.10,1,Sri Lanka,Colombo (SSC),1999-08-29,India,True,True
128,186,1,221,150,20,3,124.00,1,New Zealand,Hyderabad (Deccan),1999-11-08,India,True,True
143,122,0,195,138,12,0,88.40,2,South Africa,Vadodara,2000-03-17,India,True,True
155,101,0,-,140,3,1,72.14,1,Sri Lanka,Sharjah,2000-10-20,Sri Lanka,False,True
162,146,0,200,153,15,2,95.42,1,Zimbabwe,Jodhpur,2000-12-08,Zimbabwe,False,True
167,139,0,197,125,19,0,111.20,1,Australia,Indore,2001-03-31,India,True,True
173,122,1,210,131,12,1,93.12,2,West Indies,Harare,2001-07-04,India,True,True
175,101,0,209,129,9,0,78.29,1,South Africa,Johannesburg,2001-10-05,South Africa,False,True
179,146,0,186,132,17,0,110.60,1,Kenya,Paarl,2001-10-24,India,True,True
191,105,1,167,108,8,1,97.22,1,England,Chester-le-Street,2002-07-04,no result,False,True
194,113,0,141,102,12,1,110.78,1,Sri Lanka,Bristol,2002-07-11,India,True,True
206,152,0,193,151,18,0,100.66,1,Namibia,Pietermaritzburg,2003-02-23,India,True,True
215,100,0,158,119,9,1,84.03,1,Australia,Gwalior,2003-10-26,India,True,True
219,102,0,124,91,12,1,112.08,1,New Zealand,Hyderabad (Deccan),2003-11-15,India,True,True
229,141,0,173,135,17,1,104.44,2,Pakistan,Rawalpindi,2004-03-16,Pakistan,False,True
245,123,0,192,130,12,2,94.61,1,Pakistan,Ahmedabad,2005-04-12,Pakistan,False,True
258,100,0,188,113,10,1,88.49,1,Pakistan,Peshawar,2006-02-06,Pakistan,False,True
262,141,1,-,148,13,5,95.27,1,West Indies,Kuala Lumpur,2006-09-14,West Indies,False,True
276,100,1,110,76,10,1,131.57,1,West Indies,Vadodara,2007-01-31,India,True,True
313,117,1,235,120,10,0,97.50,2,Australia,Sydney,2008-03-02,India,True,True
322,163,1,206,133,16,5,122.55,1,New Zealand,Christchurch,2009-03-08,India,True,True
325,138,0,214,133,10,1,103.75,1,Sri Lanka,Colombo (RPS),2009-09-14,India,True,True
331,175,0,210,141,19,4,124.11,2,Australia,Hyderabad (Deccan),2009-11-05,Australia,False,True
338,200,1,226,147,25,3,136.05,1,South Africa,Gwalior,2010-02-24,India,True,True
342,120,0,170,115,10,5,104.34,1,England,Bengaluru,2011-02-27,tied,False,True
345,111,0,184,101,8,3,109.90,1,South Africa,Nagpur,2011-03-12,South Africa,False,True
358,114,0,205,147,12,1,77.55,1,Bangladesh,Dhaka,2012-03-16,Bangladesh,False,True

In [ ]:
event_B = sachin_data[sachin_data['Won'] == True]

In [ ]:
final = pd.merge(event_A, event_B, how='inner')

In [ ]:
len(sachin_data)

360

In [ ]:
100* len(final)/len(event_A)

65.21739130434783

In [ ]:
sachin_data['Won'].value_counts(normalize= True)

Won
True     0.511111
False    0.488889
Name: proportion, dtype: float64

In [ ]:
#P(A∪B)=P(A)+P(B)−P(A∩B)
#What is the probability that Sachin scored more than 50 runs (Event A) or India won the match (Event B)?

In [ ]:
total_matches = len(sachin_data)

In [ ]:
event_A = sachin_data[sachin_data['runs'] > 50]

In [ ]:
event_B = sachin_data[sachin_data['Won'] == True]

In [ ]:
intersection = pd.merge(event_A, event_B, how='inner')

In [ ]:
P_A = len(event_A) / total_matches
P_B = len(event_B) / total_matches
P_A_intersection_B = len(intersection) / total_matches

In [ ]:
P_A_union_B = P_A + P_B - P_A_intersection_B

In [ ]:
P_A_union_B

0.6388888888888888

In [ ]:
# What is the probability that Sachin scored more than 50 runs (Event A)
# and India won the match (Event B)?

In [ ]:
#P(A∩B)=P(A)⋅P(B∣A)
## Event A: Sachin scored > 50 runs
P_A

0.33055555555555555

In [ ]:
conditional_data = sachin_data[sachin_data['runs'] > 50]

In [ ]:
conditional_data[conditional_data['Won']== True]

,runs,NotOut,mins,bf,fours,sixes,sr,Inns,Opp,Ground,Date,Winner,Won,century
5,112,1,137,107,15,1,104.67,2,Sri Lanka,Sharjah,1995-04-09,India,True,True
12,127,1,175,138,15,1,92.02,2,Kenya,Cuttack,1996-02-18,India,True,True
13,70,0,137,91,8,0,76.92,2,West Indies,Gwalior,1996-02-21,India,True,False
23,118,0,-,140,8,2,84.28,1,Pakistan,Sharjah,1996-04-15,India,True,True
30,89,1,-,89,9,3,100.00,2,Pakistan,Toronto,1996-09-16,India,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,96,1,187,104,13,0,92.30,2,Sri Lanka,Cuttack,2009-12-21,India,True,False
338,200,1,226,147,25,3,136.05,1,South Africa,Gwalior,2010-02-24,India,True,True
347,53,0,93,68,7,0,77.94,2,Australia,Ahmedabad,2011-03-24,India,True,False
348,85,0,160,115,11,0,73.91,1,Pakistan,Mohali,2011-03-30,India,True,False
359,52,0,93,48,5,1,108.33,2,Pakistan,Dhaka,2012-03-18,India,True,False

In [ ]:
P_B_given_A = len(conditional_data[conditional_data['Won'] == True]) / len(event_A)

# Applying the multiplication rule
P_A_intersection_B = P_A * P_B_given_A

In [ ]:
P_A_intersection_B

0.20277777777777778

In [ ]:
##What is the probability that Sachin Tendulkar scored a century?
sachin_data.head()

,runs,NotOut,mins,bf,fours,sixes,sr,Inns,Opp,Ground,Date,Winner,Won,century
0,13,0,30,15,3,0,86.66,1,New Zealand,Napier,1995-02-16,New Zealand,False,False
1,37,0,75,51,3,1,72.54,2,South Africa,Hamilton,1995-02-18,South Africa,False,False
2,47,0,65,40,7,0,117.50,2,Australia,Dunedin,1995-02-22,India,True,False
3,48,0,37,30,9,1,160.00,2,Bangladesh,Sharjah,1995-04-05,India,True,False
4,4,0,13,9,1,0,44.44,2,Pakistan,Sharjah,1995-04-07,Pakistan,False,False

In [ ]:
len(sachin_data[sachin_data['century'] == True])

46

In [ ]:
len(sachin_data[sachin_data['century'] == True])/len(sachin_data)

0.12777777777777777

In [ ]:
#what is the probability that he scored more than 50 runs and hit at least one six in an ODI match?

In [ ]:
runs_50 = sachin_data[sachin_data['runs'] >50]

In [ ]:
sixes_match =sachin_data[sachin_data['sixes'] >0]

In [ ]:
len(sachin_data[(sachin_data['runs'] >50) & (sachin_data['sixes'] >0)])/len(sachin_data)

0.18888888888888888

In [ ]:
p_covid = 0.01
p_no_covid = 0.99

p_yes_given_covid = 0.8
p_yes_given_no_covid = 0.1

In [ ]:
p_yes = (p_yes_given_covid * p_covid) + (p_yes_given_no_covid * p_no_covid)

In [ ]:
p_covid_given_yes = (p_covid * p_yes_given_covid )/p_yes

In [ ]:
p_covid_given_yes

0.07476635514018691

In [ ]:
### Given that Sachin Tendulkar batted first in an ODI match, what is the probability that he scored a century?
bat_first_matches = sachin_data[sachin_data['Inns'] == 1]

In [ ]:
centuries_batting_first = bat_first_matches[bat_first_matches['century'] == True]

In [ ]:
len(centuries_batting_first)/len(bat_first_matches)

0.17647058823529413

In [ ]:
total_matches

360

In [ ]:
bat_first = len(sachin_data[sachin_data['Inns']==1])

In [ ]:
centuries_total = len(sachin_data[sachin_data['century'] == True])

In [ ]:
centuries_bat_first = len(centuries_batting_first)

In [ ]:
#P(Bat first| Century)= P(Century| Bat first)*P(Bat first)/P(Century)

In [ ]:
P_century = centuries_total / total_matches
P_century_given_bat_first = centuries_bat_first / bat_first
P_bat_first = bat_first / total_matches

In [ ]:
(P_century_given_bat_first*P_bat_first)/P_century

0.6521739130434784

In [ ]:
sachin_data['Inns']

0      1
1      2
2      2
3      2
4      2
      ..
355    2
356    2
357    1
358    1
359    2
Name: Inns, Length: 360, dtype: int64